### ISSUE TITLE
Implement fuzz test cases and integrate with a fuzzer

### ISSUE THREAD

**Issue by alessandrogario** [osql/osql-experimental#13]

**Comment by artemdinaburg** [comment]
One thing we'd like to do is integrate DeepState with the osql tests. Attempting this sounds like a benefit for both projects.

The osql tests are already in google test format, which DeepState aims to simulate.
Using a fuzzing backend with DeepState should give osql better test coverage than existing tests. It would also show whether DeepState can run on a real project, or whether there are issues preventing DeepState from being integrated into existing codebases.

**Comment by mike-myers-tob** [comment]
Ideas/points from the osquery Slack chat:
- modify the system state (fuzz the source data that acts as input to an osquery table)
- you could fuzz the filetypes that osquery reads/parses directly, such as .plist files, . `cron`, `authorized_keys`, `launchd`, `chrome_extensions`, etc. Most system state, however, is accessed via a system API.
- the osqueryd process usually runs as root so it is a possible privesc vector
- the query interface itself is not of interest for fuzzing, because access is limited to whoever controls the server, or the osquery config file. Both of those already ought to be access-limited to a small group of privileged users.
- likewise osquery doesn't accept any incoming network connections
- the Thrift API socket is also access controlled (right?)

Guido Vranken and Google are reportedly going to work on this.

**Comment by directionless** [comment]
I think the query interface probably is interesting to fuzz. Maybe less than the others, since there is some mitigation around who it's running as. But I suspect that in a lot of enterprise deployments, people with access to the management side, may not be allowed unfettered access to the devices.

**Comment by mike-myers-tob** [comment]
Related, we are working to upstream a change that enables sanitizers on the debug builds. https://github.com/osquery/osquery/pull/5628

We made a goal to do something similar on Windows. https://github.com/osquery/osquery/issues/5734

It looks like there used to be a `make fuzz` build target and it got removed? Maybe it invoked `./tools/analysis/fuzz.py`?

Guido Vranken never submitted his work, and removed it from GitHub: https://github.com/google/oss-fuzz/issues/2305#issuecomment-486221579

I'll start a new issue upstream. This is also related to the "dynamic analysis" criteria for the CII badge https://github.com/osquery/foundation/issues/17
