### ISSUE TITLE
Reintroduce support for other Linux distributions

### ISSUE THREAD

**Issue by mike-myers-tob** [osql/osql-experimental#7]
At least Ubuntu 16.04, CentOS 6, CentOS 7 are of interest. The support for these distributions was broken in osquery's `experimental` branch, with its changes to the build system.

**Comment by Smjert** [comment]
The main issue here is that previously osquery was using a custom built toolchain, so that the same compiler version was used and so that even older Linux distributions could use that toolchain.
Currently instead the system toolchain is used, and it needs a recent (but not too recent) compiler version.

We use llvm/clang 6.0.0, but I recently tried with llvm/clang 5.0.0 on Ubuntu 18.04 and it compiles fine (but it still uses libc++ 6).

I also just seen that Ubuntu 16.04 in its xenial-updates repository has up to clang 6, the only problem is that the libc++ library is old (3.7).
It is possible to quickly compile a newer one, same version as the compiler, and use that
to compile osql, though the bpf tracing code doesn't compile, so it has to be disabled from CMake and a small patch has to be done to avoid calls into that code.

With CentOS 7 there is the possibility of installing clang 5.0 using the Red Hat devtoolset and then compile libc++ as for Ubuntu, but I would need to see if there are issues using libc++ version 5 instead of 6.

For CentOS 6 I still have to check if the same devtoolset is available.

The real problem is that we could hit some bug or performance issues differences between the two major versions (5 and 6).

There are other two main ways of approaching this:

1. Try to do fully static builds.
    - Statically compile glibc and libc++ so that almost everything is included in the binary. This is not completely static because glibc might still need to load some modules dynamically (like PAM modules).
    - Statically compile libmusl and libc++. This is a fully static build, though we never tested
it.

Both solutions though have the same problem: third-party dependencies are pre-built, we don't know how (which flags etc) and with which compiler version.
Since also the third party libraries carry a statically compile glibc inside, if we want to use libmusl we would have to recompile all third-party dependencies too to use libmusl.
This is currently not possible in osql (but it's something we want to enable the developer to do).

2. Compile a custom toolchain and use it for all the platforms, like the old osquery would do. This would permit to compile osql on more platforms and with more defined behaviour, since the toolchain will be always the same.
I feel though that this might be a bigger task than the first way.

**Comment by Smjert** [comment]
A small update for CentOS 7 compilation: the compilation phase goes fine, but the system doesn't provide a static version of liblzma, so linking fails.

We can add lzma as a third party dependency to compile on the spot (as it's done for sqlite and googletest) if it's not found through find_package on the system.

**Comment by mike-myers-tob** [comment]
With the overhauls to [third-party dependencies](https://github.com/osquery/osquery/pull/5706) and [the custom toolchain](https://github.com/osquery/osquery/pull/5759), a lot of progress toward this has been made upstream. Let's track this in upstream.
